name: Main

permissions:
  contents: read

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  static-sdk:
    name: Static Linux Swift SDK
    uses: apple/swift-nio/.github/workflows/static_sdk.yml@d09ffc8ad6437bc278897279e33150d8e39ee3d5  # main as of 2026-10-03; includes Swift 6.4 inputs

  release-builds:
    name: Release builds
    uses: apple/swift-nio/.github/workflows/release_builds.yml@d09ffc8ad6437bc278897279e33150d8e39ee3d5  # main as of 2026-10-03; includes Swift 6.4 inputs
    with:
      minimum_swift_version: "6.3"
      linux_6_2_enabled: false
