name: Main

permissions:
  contents: read

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  static-sdk:
    name: Static Linux Swift SDK
    uses: apple/swift-nio/.github/workflows/static_sdk.yml@21de5f08c1a166a6dd293d0e587ad977bf8dac5d  # 2.103.0

  release-builds:
    name: Release builds
    uses: apple/swift-nio/.github/workflows/release_builds.yml@21de5f08c1a166a6dd293d0e587ad977bf8dac5d  # 2.103.0
